# -*- coding: utf-8 -*-
"""zameen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bzBfzMKBSz7YDS62zicRdxcs6N_1erjk
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

name_list = []
price_list = []
bedroom_list= []
bathroom_list = []
area_list = []
time_list = []
url = "https://www.zameen.com/Homes/Karachi-2-1.html"
r = requests.get(url)
print(r)
soup = BeautifulSoup(r.text, 'lxml')

name = soup.find_all("div", {"class": "db1aca2f"})
for n in name:
    name_list.append(n.text)

price = soup.find_all("span", {"aria-label": "Price"})
for p in price:
    price_list.append(p.text)

bedroom = soup.find_all("span", {"aria-label": "Beds"})
for b in bedroom:
    bedroom_list.append(b.text)

bathroom = soup.find_all("span", {"aria-label": "Baths"})
for b in bathroom:
    bathroom_list.append(b.text)

area = soup.find_all("span", {"aria-label": "Area"})
for a in area:
    area_list.append(a.text)

time = soup.find_all("span", {"aria-label": "Listing creation date"})
for t in time:
    time_list.append(t.text)

print("Length of name_list:", len(name_list))
print("Length of price_list:", len(price_list))
print("Length of bedroom_list:", len(bedroom_list))
print("Length of bathroom_list:", len(bathroom_list))
print("Length of area_list:", len(area_list))
print("Length of time_list:", len(time_list))

max_len = max(len(name_list), len(price_list), len(bedroom_list),
              len(bathroom_list), len(area_list), len(time_list))

# Fill missing values with "NA"
for lst in [name_list, price_list, bedroom_list, bathroom_list, area_list, time_list]:
    lst.extend(['NA'] * (max_len - len(lst)))

# Create the DataFrame
df = pd.DataFrame({
    'Name': name_list,
    'Price': price_list,
    'Bedrooms': bedroom_list,
    'Bathrooms': bathroom_list,
    'Area': area_list,
    'Time': time_list
})

# Print the DataFrame
print(df)

df.to_csv('zameen_data.csv', index=False)

from google.colab import files

files.download('zameen_data.csv')